version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU

before_build:
  - nuget restore Test.sln

build:
  project: Test.sln
  verbosity: detailed

after_build:
  - ps: .\pack.ps1
